const sourceDirectoryHelp = [
  "Directory:",
  "  Run from a Workbench project containing benchmark.yaml plus candidates/<name>/candidate.yaml.",
  "  Candidate manifests declare their files with files.path, usually files beside candidate.yaml.",
  "  Pass --dir DIR or pass benchmark.yaml, candidates/<name>, or candidates/<name>/candidate.yaml as SOURCE.",
];

export const LOCAL_DEV_OPEN_LIFECYCLE_NOTE =
  "Keep this command running while using the local web view; Ctrl-C stops the server and the page will stop working.";

const hostedWatchLifecycleNoteLines = [
  "Watching is client-side polling only.",
  "Stopping this command does not cancel the hosted run; use workbench cloud runs cancel RUN_ID to cancel it.",
];

export const HOSTED_WATCH_LIFECYCLE_NOTE = hostedWatchLifecycleNoteLines.join(" ");

const localOpenLifecycleHelp = [
  "Lifecycle:",
  "  workbench open starts a long-running local web server.",
  `  ${LOCAL_DEV_OPEN_LIFECYCLE_NOTE}`,
];

const hostedWatchLifecycleHelp = [
  "Lifecycle:",
  ...hostedWatchLifecycleNoteLines.map((line) => `  ${line}`),
];

const rootLines = [
  "Usage:",
  "  workbench <command> [options]",
  "",
  ...sourceDirectoryHelp,
  "",
  "Project:",
  "  workbench init [DIR] --skill NAME --agent ADAPTER [--from PATH] [--example] [--json]",
  "  workbench init [DIR] --command NAME [--from PATH] [--example] [--json]",
  "  workbench check [SOURCE] [--dir DIR] [--json]",
  "  workbench adapters create PATH [--dir DIR] [--json]",
  "  workbench adapters list [--dir DIR] [--json]",
  "  workbench adapters inspect ID [--dir DIR] [--json]",
  "  workbench adapters test ID|SOURCE [--dir DIR] [--request PATH] [--output DIR] [--json]",
  "",
  "Local runs:",
  "  workbench eval [SOURCE] [--dir DIR] [--candidate CANDIDATE_ID] [--runs RUNS|all] [--samples N] [--rerun] [--json]",
  "  workbench improve [SOURCE] [--dir DIR] [--from CANDIDATE_ID] [--runs RUN] [--budget N] [--samples N] [--rerun] [--json]",
  "  workbench retry TARGET_ID [--dir DIR] [--json]",
  "  workbench open [SOURCE] [--dir DIR] [--run RUN_ID] [--host HOST] [--port N] [--no-open] [--json]",
  "  workbench restore [--dir DIR] [--candidate CANDIDATE_ID] [--dry-run] [--yes] [--json]",
  "",
  "Local inspection:",
  "  workbench runs list [--dir DIR] [--json]",
  "  workbench runs show RUN_ID [--dir DIR] [--json]",
  "  workbench candidates list [--dir DIR] [--json]",
  "  workbench candidates show CANDIDATE_ID [--dir DIR] [--json]",
  "  workbench candidates files [--dir DIR] [--candidate CANDIDATE_ID] [--json]",
  "  workbench candidates preview --path PATH [--dir DIR] [--candidate CANDIDATE_ID] [--output PATH|-] [--json]",
  "  workbench traces collect [--providers codex,claude] [--since 30d] [--workspace DIR] [--limit N] [--json]",
  "  workbench traces list [--providers codex,claude] [--since 30d] [--workspace DIR] [--limit N] [--json]",
  "  workbench traces show TRACE_ID [--providers codex,claude] [--since 30d] [--workspace DIR] [--json]",
  "",
  "Remote sync:",
  "  workbench login [--base-url URL] [--no-open] [--json]",
  "  workbench logout [--json]",
  "  workbench whoami [--dir DIR] [--json]",
  "  workbench clone OWNER/BENCHMARK[@REF] [DIR] [--dry-run] [--json]",
  "  workbench remote show [--dir DIR] [--json]",
  "  workbench remote add origin OWNER/BENCHMARK[@REF] [--dir DIR] [--json]",
  "  workbench remote set-url origin OWNER/BENCHMARK[@REF] [--dir DIR] [--json]",
  "  workbench remote remove origin [--dir DIR] [--json]",
  "  workbench fetch [--dir DIR] [--json]",
  "  workbench pull [--dir DIR] [--dry-run] [--json]",
  "  workbench push [SOURCE] [--dir DIR] [--tag TAG] [--visibility public|private] [--dry-run] [--json]",
  "",
  "Hosted runs and resources:",
  "  workbench cloud eval [SOURCE] [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--base CANDIDATE_ID] [--runs RUNS|all] [--samples N] [--rerun] [--watch] [--dry-run] [--json]",
  "  workbench cloud improve [SOURCE] [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--base CANDIDATE_ID] [--runs RUN] [--budget N] [--samples N] [--rerun] [--watch] [--dry-run] [--json]",
  "  workbench cloud retry TARGET_ID [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--watch] [--interval-ms N] [--timeout-ms N] [--json]",
  "  workbench cloud open [OWNER/BENCHMARK[@REF]|RUN_ID|CANDIDATE_ID] [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--no-open] [--json]",
  "  workbench cloud watch RUN_ID [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--interval-ms N] [--timeout-ms N] [--json]",
  "  workbench cloud logs RUN_ID [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--json]",
  "  workbench cloud star OWNER/BENCHMARK [--json]",
  "  workbench cloud unstar OWNER/BENCHMARK [--json]",
  "  workbench cloud benchmarks|runs|candidates <command> [options]",
  "",
  "Auth:",
  "  workbench auth connect ADAPTER[/SLOT] [--dir DIR] [--method METHOD] [--profile PROFILE] [--profile-root DIR] [--local-only] [--json]",
  "  workbench auth disconnect ADAPTER[/SLOT] [--profile PROFILE] [--local-only] [--json]",
  "",
  "Examples:",
  "  workbench init --skill invoice-review --agent codex",
  "  workbench eval candidates/current --samples 1",
  "  workbench improve --budget 2 --samples 1",
  "  workbench retry eval_local_123 --json",
  "  workbench open --no-open --json",
  "  workbench push --tag v1",
  "  workbench cloud eval candidates/current --benchmark openbench/invoice-review@v1 --watch",
  "",
  "Environment:",
  "  WORKBENCH_API_URL sets the hosted Workbench API base URL.",
  "",
  "Default API URL:",
  "  https://v2.workbench.ai",
];

export const rootUsage = rootLines.join("\n");

function withSourceDirectoryHelp(lines: readonly string[]): string[] {
  return withHelpAfterUsage(lines, sourceDirectoryHelp);
}

function withLifecycleHelp(lines: readonly string[], lifecycleHelp: readonly string[]): string[] {
  return withHelpAfterUsage(lines, lifecycleHelp);
}

function withHelpAfterUsage(
  lines: readonly string[],
  helpLines: readonly string[],
): string[] {
  const firstBlankIndex = lines.indexOf("");
  if (firstBlankIndex < 0) {
    return [...lines, "", ...helpLines];
  }
  return [
    ...lines.slice(0, firstBlankIndex),
    "",
    ...helpLines,
    "",
    ...lines.slice(firstBlankIndex + 1),
  ];
}

const commandHelp: Record<string, string> = Object.fromEntries(Object.entries({
  init: [
    "Usage:",
    "  workbench init [DIR] --skill NAME --agent ADAPTER [--from PATH] [--example] [--json]",
    "  workbench init [DIR] --command NAME [--from PATH] [--example] [--json]",
    "",
    "Scaffold a local Workbench project. benchmark.yaml selects an engine; the built-in workbench engine owns tasks, environment, and scoring under engine.with. candidates/<name>/candidate.yaml owns files.path plus optional prepare and run behavior. Candidate manifests own improvement behavior.",
    "",
    "Examples:",
    "  workbench init --skill invoice-review --agent codex",
    "  workbench init --command command-eval",
  ],
  check: withSourceDirectoryHelp([
    "Usage:",
    "  workbench check [SOURCE] [--dir DIR] [--json]",
    "",
    "Validate benchmark.yaml, one candidate manifest.",
    "",
    "Examples:",
    "  workbench check",
    "  workbench check candidates/current --json",
  ]),
  eval: withSourceDirectoryHelp([
    "Usage:",
    "  workbench eval [SOURCE] [--dir DIR] [--candidate CANDIDATE_ID] [--runs RUNS|all] [--samples N] [--rerun] [--json]",
    "",
    "Ensure the selected local candidate run has an evaluation for the current benchmark. Completed work is reused only when candidate, run configuration, source, adapters, benchmark, and samples match; use --rerun to intentionally spend again.",
    "",
    "Examples:",
    "  workbench eval --samples 1",
    "  workbench eval candidates/current --samples 2 --json",
  ]),
  improve: withSourceDirectoryHelp([
    "Usage:",
    "  workbench improve [SOURCE] [--dir DIR] [--from CANDIDATE_ID] [--runs RUN] [--budget N] [--samples N] [--rerun] [--json]",
    "",
    "Ensure a local candidate improvement exists for the selected base, run, budget, and samples. Completed work is reused only when base, run configuration, source, adapters, benchmark, budget, and samples match; use --rerun to intentionally spend again.",
    "",
    "Examples:",
    "  workbench improve --budget 1 --samples 1",
    "  workbench improve candidates/current --from candidate_123 --json",
  ]),
  retry: withSourceDirectoryHelp([
    "Usage:",
    "  workbench retry TARGET_ID [--dir DIR] [--json]",
    "",
    "Retry a failed local run or evaluation by replaying its recorded candidate, configuration, sample count, and improve budget.",
    "",
    "Examples:",
    "  workbench retry eval_local_123 --json",
    "  workbench retry run_local_123 --dir ./my-benchmark",
  ]),
  open: withSourceDirectoryHelp(withLifecycleHelp([
    "Usage:",
    "  workbench open [SOURCE] [--dir DIR] [--run RUN_ID] [--host HOST] [--port N] [--no-open] [--json]",
    "",
    "Start the local Workbench web view for the project and keep serving it until stopped. When a run is supplied, open directly to that run. Without --run, Workbench opens the latest run when one exists.",
    "",
    "Examples:",
    "  workbench open",
    "  workbench open --run eval_local_123 --port 4317 --no-open --json",
  ], localOpenLifecycleHelp)),
  restore: withSourceDirectoryHelp([
    "Usage:",
    "  workbench restore [--dir DIR] [--candidate CANDIDATE_ID] [--dry-run] [--yes] [--json]",
    "",
    "Restore a local candidate snapshot into the candidate files directory.",
    "",
    "Examples:",
    "  workbench restore --candidate candidate_123 --dry-run",
    "  workbench restore --candidate candidate_123 --yes",
  ]),
  runs: [
    "Usage:",
    "  workbench runs <command> [options]",
    "",
    "Inspect local run history.",
    "",
    "Commands:",
    "  workbench runs list [--dir DIR] [--json]",
    "  workbench runs show RUN_ID [--dir DIR] [--json]",
    "",
    "Examples:",
    "  workbench runs list --json",
    "  workbench runs show eval_local_123 --json",
  ],
  "runs list": withSourceDirectoryHelp([
    "Usage:",
    "  workbench runs list [--dir DIR] [--json]",
    "",
    "List local runs.",
    "",
    "Examples:",
    "  workbench runs list",
    "  workbench runs list --dir ./my-benchmark --json",
  ]),
  "runs show": withSourceDirectoryHelp([
    "Usage:",
    "  workbench runs show RUN_ID [--dir DIR] [--json]",
    "",
    "Show one local run record.",
    "",
    "Examples:",
    "  workbench runs show eval_local_123",
    "  workbench runs show eval_local_123 --json",
  ]),
  candidates: [
    "Usage:",
    "  workbench candidates <command> [options]",
    "",
    "Inspect local candidates.",
    "",
    "Commands:",
    "  workbench candidates list [--dir DIR] [--json]",
    "  workbench candidates show CANDIDATE_ID [--dir DIR] [--json]",
    "  workbench candidates files [--dir DIR] [--candidate CANDIDATE_ID] [--json]",
    "  workbench candidates preview --path PATH [--dir DIR] [--candidate CANDIDATE_ID] [--output PATH|-] [--json]",
    "",
    "Examples:",
    "  workbench candidates list --json",
    "  workbench candidates preview --candidate candidate_123 --path SKILL.md --output -",
  ],
  "candidates list": withSourceDirectoryHelp([
    "Usage:",
    "  workbench candidates list [--dir DIR] [--json]",
    "",
    "List local candidates.",
    "",
    "Examples:",
    "  workbench candidates list",
    "  workbench candidates list --json",
  ]),
  "candidates show": withSourceDirectoryHelp([
    "Usage:",
    "  workbench candidates show CANDIDATE_ID [--dir DIR] [--json]",
    "",
    "Show one local candidate.",
    "",
    "Examples:",
    "  workbench candidates show candidate_123",
    "  workbench candidates show candidate_123 --json",
  ]),
  "candidates files": withSourceDirectoryHelp([
    "Usage:",
    "  workbench candidates files [--dir DIR] [--candidate CANDIDATE_ID] [--json]",
    "",
    "List files in a local candidate snapshot.",
    "",
    "Examples:",
    "  workbench candidates files --candidate candidate_123",
    "  workbench candidates files --candidate candidate_123 --json",
  ]),
  "candidates preview": withSourceDirectoryHelp([
    "Usage:",
    "  workbench candidates preview --path PATH [--dir DIR] [--candidate CANDIDATE_ID] [--output PATH|-] [--json]",
    "",
    "Preview a file from a local candidate snapshot.",
    "",
    "Examples:",
    "  workbench candidates preview --candidate candidate_123 --path SKILL.md",
    "  workbench candidates preview --candidate candidate_123 --path SKILL.md --output -",
  ]),
  clone: [
    "Usage:",
    "  workbench clone OWNER/BENCHMARK[@REF] [DIR] [--dry-run] [--json]",
    "",
    "Download a hosted benchmark project into a local Workbench project and write .workbench/origin.json.",
    "",
    "Examples:",
    "  workbench clone openbench/invoice-review",
    "  workbench clone openbench/invoice-review@v1 ./invoice-review --dry-run --json",
  ],
  remote: withSourceDirectoryHelp([
    "Usage:",
    "  workbench remote show [--dir DIR] [--json]",
    "  workbench remote add origin OWNER/BENCHMARK[@REF] [--dir DIR] [--json]",
    "  workbench remote set-url origin OWNER/BENCHMARK[@REF] [--dir DIR] [--json]",
    "  workbench remote remove origin [--dir DIR] [--json]",
    "",
    "Manage the project origin used by fetch, pull, and push.",
    "",
    "Examples:",
    "  workbench remote show --json",
    "  workbench remote add origin openbench/invoice-review@v1",
  ]),
  "remote show": withSourceDirectoryHelp([
    "Usage:",
    "  workbench remote show [--dir DIR] [--json]",
    "",
    "Show the configured origin.",
    "",
    "Examples:",
    "  workbench remote show",
    "  workbench remote show --json",
  ]),
  "remote add": withSourceDirectoryHelp([
    "Usage:",
    "  workbench remote add origin OWNER/BENCHMARK[@REF] [--dir DIR] [--json]",
    "",
    "Set the project origin.",
    "",
    "Examples:",
    "  workbench remote add origin openbench/invoice-review@v1",
    "  workbench remote add origin openbench/invoice-review --json",
  ]),
  "remote set-url": withSourceDirectoryHelp([
    "Usage:",
    "  workbench remote set-url origin OWNER/BENCHMARK[@REF] [--dir DIR] [--json]",
    "",
    "Replace the project origin.",
    "",
    "Examples:",
    "  workbench remote set-url origin openbench/invoice-review@v2",
    "  workbench remote set-url origin openbench/invoice-review@v2 --json",
  ]),
  "remote remove": withSourceDirectoryHelp([
    "Usage:",
    "  workbench remote remove origin [--dir DIR] [--json]",
    "",
    "Remove the project origin.",
    "",
    "Examples:",
    "  workbench remote remove origin",
    "  workbench remote remove origin --json",
  ]),
  fetch: withSourceDirectoryHelp([
    "Usage:",
    "  workbench fetch [--dir DIR] [--json]",
    "",
    "Download remote source into .workbench/fetch without changing project files.",
    "",
    "Examples:",
    "  workbench fetch",
    "  workbench fetch --json",
  ]),
  pull: withSourceDirectoryHelp([
    "Usage:",
    "  workbench pull [--dir DIR] [--dry-run] [--json]",
    "",
    "Update managed project source files from the configured origin.",
    "",
    "Examples:",
    "  workbench pull --dry-run",
    "  workbench pull --json",
  ]),
  push: withSourceDirectoryHelp([
    "Usage:",
    "  workbench push [SOURCE] [--dir DIR] [--tag TAG] [--visibility public|private] [--dry-run] [--json]",
    "",
    "Create or update the hosted benchmark version from local project source and write .workbench/origin.json.",
    "",
    "Examples:",
    "  workbench push --tag v1 --dry-run",
    "  workbench push candidates/current --visibility private --json",
  ]),
  login: [
    "Usage:",
    "  workbench login [--base-url URL] [--no-open] [--json]",
    "",
    "Authenticate this machine with Workbench Cloud.",
    "",
    "Examples:",
    "  workbench login",
    "  workbench login --no-open --json",
  ],
  logout: [
    "Usage:",
    "  workbench logout [--json]",
    "",
    "Remove the stored Workbench Cloud access token.",
    "",
    "Examples:",
    "  workbench logout",
    "  workbench logout --json",
  ],
  whoami: withSourceDirectoryHelp([
    "Usage:",
    "  workbench whoami [--dir DIR] [--json]",
    "",
    "Show the effective Workbench Cloud API target, login status, username, and required adapter auth status.",
    "",
    "Examples:",
    "  workbench whoami",
    "  workbench whoami --json",
  ]),
  adapters: withSourceDirectoryHelp([
    "Usage:",
    "  workbench adapters create PATH [--dir DIR] [--json]",
    "  workbench adapters list [--dir DIR] [--json]",
    "  workbench adapters inspect ID [--dir DIR] [--json]",
    "  workbench adapters test ID|SOURCE [--dir DIR] [--request PATH] [--output DIR] [--json]",
    "",
    "Create, list, inspect, and locally replay Workbench adapters. Adapter sources can be local paths, npm: package refs, or git: refs.",
    "",
    "Examples:",
    "  workbench adapters list --json",
    "  workbench adapters test codex --json",
  ]),
  "adapters create": withSourceDirectoryHelp([
    "Usage:",
    "  workbench adapters create PATH [--dir DIR] [--json]",
    "",
    "Scaffold a benchmark-contained adapter source.",
    "",
    "Examples:",
    "  workbench adapters create adapters/my-agent",
    "  workbench adapters create adapters/my-agent --json",
  ]),
  "adapters list": withSourceDirectoryHelp([
    "Usage:",
    "  workbench adapters list [--dir DIR] [--json]",
    "",
    "List default and project-declared adapters.",
    "",
    "Examples:",
    "  workbench adapters list",
    "  workbench adapters list --json",
  ]),
  "adapters inspect": withSourceDirectoryHelp([
    "Usage:",
    "  workbench adapters inspect ID [--dir DIR] [--json]",
    "",
    "Show one adapter manifest and resolved source.",
    "",
    "Examples:",
    "  workbench adapters inspect codex",
    "  workbench adapters inspect adapters/my-agent --json",
  ]),
  "adapters test": withSourceDirectoryHelp([
    "Usage:",
    "  workbench adapters test ID|SOURCE [--dir DIR] [--request PATH] [--output DIR] [--json]",
    "",
    "Validate an adapter manifest, or replay its command locally when --request is provided. Without --output, replay uses a temporary output directory.",
    "",
    "Examples:",
    "  workbench adapters test codex --json",
    "  workbench adapters test adapters/my-agent --request request.json --output out/adapter-test",
  ]),
  traces: [
    "Usage:",
    "  workbench traces collect [--providers codex,claude] [--since 30d] [--workspace DIR] [--limit N] [--json]",
    "  workbench traces list [--providers codex,claude] [--since 30d] [--workspace DIR] [--limit N] [--json]",
    "  workbench traces show TRACE_ID [--providers codex,claude] [--since 30d] [--workspace DIR] [--json]",
    "",
    "Inspect local installed-agent traces without calling an LLM.",
    "",
    "Examples:",
    "  workbench traces list --limit 10 --json",
    "  workbench traces show codex:SESSION:TRACE --json",
  ],
  "traces collect": [
    "Usage:",
    "  workbench traces collect [--providers codex,claude] [--since 30d] [--workspace DIR] [--limit N] [--json]",
    "",
    "Recover recent local Codex and Claude Code sessions to stdout without calling an LLM. --limit defaults to 3 per provider and output reports when matches were capped.",
    "",
    "Examples:",
    "  workbench traces collect --limit 5 --json",
    "  workbench traces collect --providers codex --workspace . --since 14d",
  ],
  "traces list": [
    "Usage:",
    "  workbench traces list [--providers codex,claude] [--since 30d] [--workspace DIR] [--limit N] [--json]",
    "",
    "List recent local Codex and Claude Code sessions as compact trace rows with ids for follow-up inspection.",
    "",
    "Examples:",
    "  workbench traces list --limit 10 --json",
    "  workbench traces list --providers claude --workspace .",
  ],
  "traces show": [
    "Usage:",
    "  workbench traces show TRACE_ID [--providers codex,claude] [--since 30d] [--workspace DIR] [--json]",
    "",
    "Show one selected local trace digest by exact id.",
    "",
    "Examples:",
    "  workbench traces show codex:SESSION:TRACE --json",
    "  workbench traces show claude:SESSION:TRACE --workspace .",
  ],
  auth: [
    "Usage:",
    "  workbench auth <command> [options]",
    "",
    "Connect adapter auth for local and hosted runs.",
    "",
    "Commands:",
    "  workbench auth connect ADAPTER[/SLOT] [--dir DIR] [--method METHOD] [--profile PROFILE] [--profile-root DIR] [--local-only] [--json]",
    "  workbench auth disconnect ADAPTER[/SLOT] [--profile PROFILE] [--local-only] [--json]",
    "",
    "Examples:",
    "  workbench auth connect codex --method oauth --json",
    "  workbench auth disconnect codex --local-only",
  ],
  "auth connect": [
    "Usage:",
    "  workbench auth connect ADAPTER[/SLOT] [--dir DIR] [--method METHOD] [--profile PROFILE] [--profile-root DIR] [--local-only] [--json]",
    "",
    "Connect adapter auth using a manifest-supported method.",
    "",
    "Examples:",
    "  workbench auth connect codex --method oauth --json",
    "  workbench auth connect claude --method api-key --profile default --local-only",
  ],
  "auth disconnect": [
    "Usage:",
    "  workbench auth disconnect ADAPTER[/SLOT] [--profile PROFILE] [--local-only] [--json]",
    "",
    "Disconnect adapter auth locally and, when logged in, in hosted Workbench.",
    "",
    "Examples:",
    "  workbench auth disconnect codex --local-only",
    "  workbench auth disconnect claude --profile default --json",
  ],
  cloud: [
    "Usage:",
    "  workbench cloud <command> [options]",
    "",
    "Hosted Workbench Cloud execution and resource commands.",
    "",
    "Commands:",
    "  workbench cloud eval [SOURCE] [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--base CANDIDATE_ID] [--runs RUNS|all] [--samples N] [--rerun] [--watch] [--dry-run] [--json]",
    "  workbench cloud improve [SOURCE] [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--base CANDIDATE_ID] [--runs RUN] [--budget N] [--samples N] [--rerun] [--watch] [--dry-run] [--json]",
    "  workbench cloud retry TARGET_ID [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--watch] [--interval-ms N] [--timeout-ms N] [--json]",
    "  workbench cloud open [OWNER/BENCHMARK[@REF]|RUN_ID|CANDIDATE_ID] [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--no-open] [--json]",
    "  workbench cloud watch RUN_ID [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--interval-ms N] [--timeout-ms N] [--json]",
    "  workbench cloud logs RUN_ID [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--json]",
    "  workbench cloud star OWNER/BENCHMARK [--json]",
    "  workbench cloud unstar OWNER/BENCHMARK [--json]",
    "  workbench cloud benchmarks|runs|candidates <command> [options]",
    "",
    "Examples:",
    "  workbench cloud eval candidates/current --benchmark openbench/invoice-review@v1 --dry-run --json",
    "  workbench cloud retry run_123 --benchmark openbench/invoice-review --watch",
    "  workbench cloud runs list --benchmark openbench/invoice-review --json",
  ],
  "cloud star": [
    "Usage:",
    "  workbench cloud star OWNER/BENCHMARK [--json]",
    "",
    "Star a hosted benchmark.",
    "",
    "Examples:",
    "  workbench cloud star openbench/invoice-review",
    "  workbench cloud star openbench/invoice-review --json",
  ],
  "cloud unstar": [
    "Usage:",
    "  workbench cloud unstar OWNER/BENCHMARK [--json]",
    "",
    "Remove your star from a hosted benchmark.",
    "",
    "Examples:",
    "  workbench cloud unstar openbench/invoice-review",
    "  workbench cloud unstar openbench/invoice-review --json",
  ],
  "cloud eval": withSourceDirectoryHelp(withLifecycleHelp([
    "Usage:",
    "  workbench cloud eval [SOURCE] [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--base CANDIDATE_ID] [--runs RUNS|all] [--samples N] [--rerun] [--watch] [--dry-run] [--json]",
    "",
    "Ensure a hosted evaluation exists for the selected candidate run. Completed hosted work is reused only when candidate, run configuration, source, adapters, benchmark, and samples match; use --rerun to intentionally spend again.",
    "",
    "Examples:",
    "  workbench cloud eval candidates/current --benchmark openbench/invoice-review@v1 --dry-run --json",
    "  workbench cloud eval --benchmark openbench/invoice-review --watch",
  ], hostedWatchLifecycleHelp)),
  "cloud improve": withSourceDirectoryHelp(withLifecycleHelp([
    "Usage:",
    "  workbench cloud improve [SOURCE] [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--base CANDIDATE_ID] [--runs RUN] [--budget N] [--samples N] [--rerun] [--watch] [--dry-run] [--json]",
    "",
    "Ensure a hosted candidate improvement exists for the selected base, run, budget, and samples. Completed work is reused only when base, run configuration, source, adapters, benchmark, budget, and samples match; use --rerun to intentionally spend again.",
    "",
    "Examples:",
    "  workbench cloud improve --benchmark openbench/invoice-review --dry-run",
    "  workbench cloud improve candidates/current --watch --json",
  ], hostedWatchLifecycleHelp)),
  "cloud retry": withSourceDirectoryHelp(withLifecycleHelp([
    "Usage:",
    "  workbench cloud retry TARGET_ID [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--watch] [--interval-ms N] [--timeout-ms N] [--json]",
    "",
    "Retry a failed hosted run or evaluation by replaying its recorded candidate, configuration, sample count, and improve budget.",
    "",
    "Examples:",
    "  workbench cloud retry run_123 --benchmark openbench/invoice-review --watch",
    "  workbench cloud retry eval_123 --json",
  ], hostedWatchLifecycleHelp)),
  "cloud open": [
    "Usage:",
    "  workbench cloud open [OWNER/BENCHMARK[@REF]|RUN_ID|CANDIDATE_ID] [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--no-open] [--json]",
    "",
    "Print and open the hosted Workbench URL.",
    "",
    "Examples:",
    "  workbench cloud open openbench/invoice-review --no-open",
    "  workbench cloud open run_123 --benchmark openbench/invoice-review --json",
  ],
  "cloud watch": withSourceDirectoryHelp(withLifecycleHelp([
    "Usage:",
    "  workbench cloud watch RUN_ID [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--interval-ms N] [--timeout-ms N] [--json]",
    "",
    "Poll a hosted run until it finishes.",
    "",
    "Examples:",
    "  workbench cloud watch run_123 --benchmark openbench/invoice-review",
    "  workbench cloud watch run_123 --interval-ms 5000 --timeout-ms 600000 --json",
  ], hostedWatchLifecycleHelp)),
  "cloud logs": withSourceDirectoryHelp([
    "Usage:",
    "  workbench cloud logs RUN_ID [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--json]",
    "",
    "Show hosted run job statuses and errors.",
    "",
    "Examples:",
    "  workbench cloud logs run_123 --benchmark openbench/invoice-review",
    "  workbench cloud logs run_123 --json",
  ]),
  "cloud benchmarks": [
    "Usage:",
    "  workbench cloud benchmarks <command> [options]",
    "",
    "Hosted benchmark resource commands.",
    "",
    "Commands:",
    "  workbench cloud benchmarks list [--json]",
    "  workbench cloud benchmarks show OWNER/BENCHMARK [--json]",
    "  workbench cloud benchmarks versions OWNER/BENCHMARK [--json]",
    "  workbench cloud benchmarks starred [--json]",
    "  workbench cloud benchmarks delete OWNER/BENCHMARK [--dir DIR] [--dry-run] [--json]",
    "",
    "Examples:",
    "  workbench cloud benchmarks list --json",
    "  workbench cloud benchmarks show openbench/invoice-review",
  ],
  "cloud runs": [
    "Usage:",
    "  workbench cloud runs <command> [options]",
    "",
    "Hosted run resource commands.",
    "",
    "Commands:",
    "  workbench cloud runs list [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--json]",
    "  workbench cloud runs show RUN_ID [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--json]",
    "  workbench cloud runs cancel RUN_ID [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--json]",
    "",
    "Examples:",
    "  workbench cloud runs list --benchmark openbench/invoice-review --json",
    "  workbench cloud runs show run_123 --benchmark openbench/invoice-review",
  ],
  "cloud candidates": [
    "Usage:",
    "  workbench cloud candidates <command> [options]",
    "",
    "Hosted candidate resource commands.",
    "",
    "Commands:",
    "  workbench cloud candidates list [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--json]",
    "  workbench cloud candidates show CANDIDATE_ID [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--json]",
    "  workbench cloud candidates files CANDIDATE_ID [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--json]",
    "  workbench cloud candidates preview CANDIDATE_ID --path PATH [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--output PATH|-] [--json]",
    "  workbench cloud candidates pull CANDIDATE_ID [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--out DIR] [--json]",
    "  workbench cloud candidates publish CANDIDATE_ID [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--json]",
    "  workbench cloud candidates unpublish CANDIDATE_ID [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--json]",
    "",
    "Examples:",
    "  workbench cloud candidates list --benchmark openbench/invoice-review --json",
    "  workbench cloud candidates preview candidate_123 --path SKILL.md --output -",
  ],
}).map(([key, lines]) => [key, lines.join("\n")]));

export function commandUsage(commandPath: string): string | null {
  return commandHelp[commandPath] ?? cloudNestedCommandUsage(commandPath);
}

const hostedCommandHelp: Record<string, string> = Object.fromEntries(Object.entries({
  "benchmarks list": [
    "Usage:",
    "  workbench cloud benchmarks list [--json]",
    "",
    "List public hosted benchmarks.",
    "",
    "Examples:",
    "  workbench cloud benchmarks list",
    "  workbench cloud benchmarks list --json",
  ],
  "benchmarks show": [
    "Usage:",
    "  workbench cloud benchmarks show OWNER/BENCHMARK [--json]",
    "",
    "Show one hosted benchmark.",
    "",
    "Examples:",
    "  workbench cloud benchmarks show openbench/invoice-review",
    "  workbench cloud benchmarks show openbench/invoice-review --json",
  ],
  "benchmarks versions": [
    "Usage:",
    "  workbench cloud benchmarks versions OWNER/BENCHMARK [--json]",
    "",
    "List hosted benchmark versions.",
    "",
    "Examples:",
    "  workbench cloud benchmarks versions openbench/invoice-review",
    "  workbench cloud benchmarks versions openbench/invoice-review --json",
  ],
  "benchmarks starred": [
    "Usage:",
    "  workbench cloud benchmarks starred [--json]",
    "",
    "List benchmarks starred by the current user.",
    "",
    "Examples:",
    "  workbench cloud benchmarks starred",
    "  workbench cloud benchmarks starred --json",
  ],
  "benchmarks delete": [
    "Usage:",
    "  workbench cloud benchmarks delete OWNER/BENCHMARK [--dir DIR] [--dry-run] [--json]",
    "",
    "Delete a hosted benchmark project that you own.",
    "",
    "Examples:",
    "  workbench cloud benchmarks delete alice/invoice-review --dry-run",
    "  workbench cloud benchmarks delete alice/invoice-review --json",
  ],
  "runs list": [
    "Usage:",
    "  workbench cloud runs list [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--json]",
    "",
    "List hosted runs.",
    "",
    "Examples:",
    "  workbench cloud runs list --benchmark openbench/invoice-review",
    "  workbench cloud runs list --benchmark openbench/invoice-review --json",
  ],
  "runs show": [
    "Usage:",
    "  workbench cloud runs show RUN_ID [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--json]",
    "",
    "Show one hosted run.",
    "",
    "Examples:",
    "  workbench cloud runs show run_123 --benchmark openbench/invoice-review",
    "  workbench cloud runs show run_123 --json",
  ],
  "runs cancel": [
    "Usage:",
    "  workbench cloud runs cancel RUN_ID [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--json]",
    "",
    "Cancel a hosted run.",
    "",
    "Examples:",
    "  workbench cloud runs cancel run_123 --benchmark openbench/invoice-review",
    "  workbench cloud runs cancel run_123 --json",
  ],
  "candidates list": [
    "Usage:",
    "  workbench cloud candidates list [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--json]",
    "",
    "List hosted candidates.",
    "",
    "Examples:",
    "  workbench cloud candidates list --benchmark openbench/invoice-review",
    "  workbench cloud candidates list --json",
  ],
  "candidates show": [
    "Usage:",
    "  workbench cloud candidates show CANDIDATE_ID [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--json]",
    "",
    "Show one hosted candidate.",
    "",
    "Examples:",
    "  workbench cloud candidates show candidate_123 --benchmark openbench/invoice-review",
    "  workbench cloud candidates show candidate_123 --json",
  ],
  "candidates files": [
    "Usage:",
    "  workbench cloud candidates files CANDIDATE_ID [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--json]",
    "",
    "List files in a hosted candidate snapshot.",
    "",
    "Examples:",
    "  workbench cloud candidates files candidate_123 --benchmark openbench/invoice-review",
    "  workbench cloud candidates files candidate_123 --json",
  ],
  "candidates preview": [
    "Usage:",
    "  workbench cloud candidates preview CANDIDATE_ID --path PATH [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--output PATH|-] [--json]",
    "",
    "Preview a file from a hosted candidate snapshot.",
    "",
    "Examples:",
    "  workbench cloud candidates preview candidate_123 --path SKILL.md --output -",
    "  workbench cloud candidates preview candidate_123 --path SKILL.md --benchmark openbench/invoice-review",
  ],
  "candidates pull": [
    "Usage:",
    "  workbench cloud candidates pull CANDIDATE_ID [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--out DIR] [--json]",
    "",
    "Download hosted candidate files.",
    "",
    "Examples:",
    "  workbench cloud candidates pull candidate_123 --out ./candidate-files",
    "  workbench cloud candidates pull candidate_123 --benchmark openbench/invoice-review --json",
  ],
  "candidates publish": [
    "Usage:",
    "  workbench cloud candidates publish CANDIDATE_ID [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--json]",
    "",
    "Make a hosted candidate public.",
    "",
    "Examples:",
    "  workbench cloud candidates publish candidate_123 --benchmark openbench/invoice-review",
    "  workbench cloud candidates publish candidate_123 --json",
  ],
  "candidates unpublish": [
    "Usage:",
    "  workbench cloud candidates unpublish CANDIDATE_ID [--dir DIR] [--benchmark OWNER/BENCHMARK[@REF]] [--json]",
    "",
    "Make a hosted candidate private.",
    "",
    "Examples:",
    "  workbench cloud candidates unpublish candidate_123 --benchmark openbench/invoice-review",
    "  workbench cloud candidates unpublish candidate_123 --json",
  ],
}).map(([key, lines]) => [key, lines.join("\n")]));

function cloudNestedCommandUsage(commandPath: string): string | null {
  if (!commandPath.startsWith("cloud ")) {
    return null;
  }
  const withoutCloud = commandPath.slice("cloud ".length);
  return hostedCommandHelp[withoutCloud] ?? null;
}
