const sourceDirectoryHelp = [
  "Directory:",
  "  Run from a Workbench project containing benchmark.yaml plus candidates/<name>/candidate.yaml.",
  "  Candidate manifests declare their files with files.path, usually files beside candidate.yaml.",
  "  Pass --dir DIR or pass benchmark.yaml, candidates/<name>, or candidates/<name>/candidate.yaml as SOURCE.",
];

export const LOCAL_DEV_OPEN_LIFECYCLE_NOTE =
  "Keep this command running while using the local web view; Ctrl-C stops the server and the page will stop working.";

const hostedWatchLifecycleNoteLines = [
  "Watching is client-side polling only.",
  "Stopping this command does not cancel the hosted run.",
];

export const HOSTED_WATCH_LIFECYCLE_NOTE = hostedWatchLifecycleNoteLines.join(" ");

const localOpenLifecycleHelp = [
  "Lifecycle:",
  "  workbench open starts a long-running local web server.",
  `  ${LOCAL_DEV_OPEN_LIFECYCLE_NOTE}`,
];

const hostedWatchLifecycleHelp = [
  "Lifecycle:",
  ...hostedWatchLifecycleNoteLines.map((line) => `  ${line}`),
];

const rootLines = [
  "Usage:",
  "  workbench <command> [options]",
  "",
  ...sourceDirectoryHelp,
  "",
  "Project:",
  "  workbench init [DIR] --skill NAME --agent ADAPTER [--from PATH] [--example] [--json]",
  "  workbench init [DIR] --command NAME [--from PATH] [--example] [--json]",
  "  workbench check [SOURCE] [--dir DIR] [--json]",
  "  workbench adapters create PATH [--dir DIR] [--json]",
  "  workbench adapters list [--dir DIR] [--json]",
  "  workbench adapters inspect ID [--dir DIR] [--json]",
  "  workbench adapters test ID|SOURCE [--dir DIR] [--request PATH] [--output DIR] [--json]",
  "",
  "Runs:",
  "  workbench eval [SOURCE] [--dir DIR] [--hosted] [--benchmark OWNER/BENCHMARK] [--candidate CANDIDATE_ID] [--base CANDIDATE_ID] [--runs RUNS|all] [--samples N] [--rerun] [--watch] [--dry-run] [--json]",
  "  workbench improve [SOURCE] [--dir DIR] [--hosted] [--benchmark OWNER/BENCHMARK] [--from CANDIDATE_ID] [--base CANDIDATE_ID] [--runs RUN] [--budget N] [--samples N] [--rerun] [--watch] [--dry-run] [--json]",
  "  workbench retry TARGET_ID [--dir DIR] [--hosted] [--benchmark OWNER/BENCHMARK] [--watch] [--interval-ms N] [--timeout-ms N] [--json]",
  "  workbench open [SOURCE|OWNER/BENCHMARK|RUN_ID|CANDIDATE_ID] [--dir DIR] [--hosted] [--benchmark OWNER/BENCHMARK] [--run RUN_ID] [--host HOST] [--port N] [--no-open] [--json]",
  "  workbench restore [--dir DIR] [--candidate CANDIDATE_ID] [--dry-run] [--yes] [--json]",
  "",
  "Local inspection:",
  "  workbench runs list [--dir DIR] [--json]",
  "  workbench runs show RUN_ID [--dir DIR] [--json]",
  "  workbench candidates list [--dir DIR] [--json]",
  "  workbench candidates show CANDIDATE_ID [--dir DIR] [--json]",
  "  workbench candidates files [--dir DIR] [--candidate CANDIDATE_ID] [--json]",
  "  workbench candidates preview --path PATH [--dir DIR] [--candidate CANDIDATE_ID] [--output PATH|-] [--json]",
  "  workbench traces collect [--providers codex,claude] [--since 30d] [--workspace DIR] [--limit N] [--json]",
  "  workbench traces list [--providers codex,claude] [--since 30d] [--workspace DIR] [--limit N] [--json]",
  "  workbench traces show TRACE_ID [--providers codex,claude] [--since 30d] [--workspace DIR] [--json]",
  "",
  "Remote:",
  "  workbench login [--base-url URL] [--no-open] [--json]",
  "  workbench logout [--json]",
  "  workbench whoami [--dir DIR] [--json]",
  "  workbench clone OWNER/BENCHMARK [DIR] [--dry-run] [--json]",
  "  workbench pull [--dir DIR] [--dry-run] [--json]",
  "  workbench push [SOURCE] [--dir DIR] [--visibility public|private] [--dry-run] [--json]",
  "",
  "Auth:",
  "  workbench auth connect ADAPTER[/SLOT] [--dir DIR] [--method METHOD] [--profile PROFILE] [--profile-root DIR] [--local-only] [--json]",
  "  workbench auth disconnect ADAPTER[/SLOT] [--profile PROFILE] [--local-only] [--json]",
  "",
  "Examples:",
  "  workbench init --skill invoice-review --agent codex",
  "  workbench eval candidates/current --samples 1",
  "  workbench improve --budget 2 --samples 1",
  "  workbench retry eval_local_123 --json",
  "  workbench open --no-open --json",
  "  workbench push",
  "  workbench eval --hosted candidates/current --benchmark openbench/invoice-review --watch",
  "",
  "Environment:",
  "  WORKBENCH_API_URL sets the hosted Workbench API base URL.",
  "",
  "Default API URL:",
  "  https://v2.workbench.ai",
];

export const rootUsage = rootLines.join("\n");

function withSourceDirectoryHelp(lines: readonly string[]): string[] {
  return withHelpAfterUsage(lines, sourceDirectoryHelp);
}

function withLifecycleHelp(lines: readonly string[], lifecycleHelp: readonly string[]): string[] {
  return withHelpAfterUsage(lines, lifecycleHelp);
}

function withHelpAfterUsage(
  lines: readonly string[],
  helpLines: readonly string[],
): string[] {
  const firstBlankIndex = lines.indexOf("");
  if (firstBlankIndex < 0) {
    return [...lines, "", ...helpLines];
  }
  return [
    ...lines.slice(0, firstBlankIndex),
    "",
    ...helpLines,
    "",
    ...lines.slice(firstBlankIndex + 1),
  ];
}

const commandHelp: Record<string, string> = Object.fromEntries(Object.entries({
  init: [
    "Usage:",
    "  workbench init [DIR] --skill NAME --agent ADAPTER [--from PATH] [--example] [--json]",
    "  workbench init [DIR] --command NAME [--from PATH] [--example] [--json]",
    "",
    "Scaffold a local Workbench project. benchmark.yaml selects an engine; the built-in workbench engine owns tasks, environment, and scoring under engine.with. candidates/<name>/candidate.yaml owns files.path plus optional prepare and run behavior. Candidate manifests own improvement behavior.",
    "",
    "Examples:",
    "  workbench init --skill invoice-review --agent codex",
    "  workbench init --command command-eval",
  ],
  check: withSourceDirectoryHelp([
    "Usage:",
    "  workbench check [SOURCE] [--dir DIR] [--json]",
    "",
    "Validate benchmark.yaml, one candidate manifest.",
    "",
    "Examples:",
    "  workbench check",
    "  workbench check candidates/current --json",
  ]),
  eval: withSourceDirectoryHelp(withLifecycleHelp([
    "Usage:",
    "  workbench eval [SOURCE] [--dir DIR] [--candidate CANDIDATE_ID] [--runs RUNS|all] [--samples N] [--rerun] [--json]",
    "  workbench eval --hosted [SOURCE] [--dir DIR] [--benchmark OWNER/BENCHMARK] [--base CANDIDATE_ID] [--runs RUNS|all] [--samples N] [--rerun] [--watch] [--dry-run] [--json]",
    "",
    "Ensure the selected candidate run has an evaluation for the current benchmark. Without --hosted, execution writes local records. With --hosted, Workbench starts or reuses a hosted run against the configured remote or --benchmark target. Completed work is reused only when candidate, run configuration, source, adapters, benchmark, and samples match; use --rerun to intentionally spend again.",
    "",
    "Examples:",
    "  workbench eval --samples 1",
    "  workbench eval --hosted candidates/current --samples 1 --watch --json",
    "  workbench eval candidates/current --samples 2 --json",
  ], hostedWatchLifecycleHelp)),
  improve: withSourceDirectoryHelp(withLifecycleHelp([
    "Usage:",
    "  workbench improve [SOURCE] [--dir DIR] [--from CANDIDATE_ID] [--runs RUN] [--budget N] [--samples N] [--rerun] [--json]",
    "  workbench improve --hosted [SOURCE] [--dir DIR] [--benchmark OWNER/BENCHMARK] [--base CANDIDATE_ID] [--runs RUN] [--budget N] [--samples N] [--rerun] [--watch] [--dry-run] [--json]",
    "",
    "Ensure a candidate improvement exists for the selected base, run, budget, and samples. Without --hosted, execution writes local records. With --hosted, Workbench starts or reuses hosted work against the configured remote or --benchmark target. Completed work is reused only when base, run configuration, source, adapters, benchmark, budget, and samples match; use --rerun to intentionally spend again.",
    "",
    "Examples:",
    "  workbench improve --budget 1 --samples 1",
    "  workbench improve --hosted candidates/current --budget 1 --samples 1 --watch --json",
    "  workbench improve candidates/current --from candidate_123 --json",
  ], hostedWatchLifecycleHelp)),
  retry: withSourceDirectoryHelp(withLifecycleHelp([
    "Usage:",
    "  workbench retry TARGET_ID [--dir DIR] [--json]",
    "  workbench retry --hosted TARGET_ID [--dir DIR] [--benchmark OWNER/BENCHMARK] [--watch] [--interval-ms N] [--timeout-ms N] [--json]",
    "",
    "Retry a failed run or evaluation by replaying its recorded candidate, configuration, sample count, and improve budget. Use --hosted for hosted records.",
    "",
    "Examples:",
    "  workbench retry eval_local_123 --json",
    "  workbench retry --hosted run_123 --watch --json",
    "  workbench retry run_local_123 --dir ./my-benchmark",
  ], hostedWatchLifecycleHelp)),
  open: withSourceDirectoryHelp(withLifecycleHelp([
    "Usage:",
    "  workbench open [SOURCE] [--dir DIR] [--run RUN_ID] [--host HOST] [--port N] [--no-open] [--json]",
    "  workbench open --hosted [OWNER/BENCHMARK|RUN_ID|CANDIDATE_ID] [--dir DIR] [--benchmark OWNER/BENCHMARK] [--no-open] [--json]",
    "",
    "Start the local Workbench web view for the project and keep serving it until stopped. With --hosted, print and optionally open the hosted project URL instead.",
    "",
    "Examples:",
    "  workbench open",
    "  workbench open --hosted --no-open --json",
    "  workbench open --run eval_local_123 --port 4317 --no-open --json",
  ], localOpenLifecycleHelp)),
  restore: withSourceDirectoryHelp([
    "Usage:",
    "  workbench restore [--dir DIR] [--candidate CANDIDATE_ID] [--dry-run] [--yes] [--json]",
    "",
    "Restore a local candidate snapshot into the candidate files directory.",
    "",
    "Examples:",
    "  workbench restore --candidate candidate_123 --dry-run",
    "  workbench restore --candidate candidate_123 --yes",
  ]),
  runs: [
    "Usage:",
    "  workbench runs <command> [options]",
    "",
    "Inspect local run history.",
    "",
    "Commands:",
    "  workbench runs list [--dir DIR] [--json]",
    "  workbench runs show RUN_ID [--dir DIR] [--json]",
    "",
    "Examples:",
    "  workbench runs list --json",
    "  workbench runs show eval_local_123 --json",
  ],
  "runs list": withSourceDirectoryHelp([
    "Usage:",
    "  workbench runs list [--dir DIR] [--json]",
    "",
    "List local runs.",
    "",
    "Examples:",
    "  workbench runs list",
    "  workbench runs list --dir ./my-benchmark --json",
  ]),
  "runs show": withSourceDirectoryHelp([
    "Usage:",
    "  workbench runs show RUN_ID [--dir DIR] [--json]",
    "",
    "Show one local run record.",
    "",
    "Examples:",
    "  workbench runs show eval_local_123",
    "  workbench runs show eval_local_123 --json",
  ]),
  candidates: [
    "Usage:",
    "  workbench candidates <command> [options]",
    "",
    "Inspect local candidates.",
    "",
    "Commands:",
    "  workbench candidates list [--dir DIR] [--json]",
    "  workbench candidates show CANDIDATE_ID [--dir DIR] [--json]",
    "  workbench candidates files [--dir DIR] [--candidate CANDIDATE_ID] [--json]",
    "  workbench candidates preview --path PATH [--dir DIR] [--candidate CANDIDATE_ID] [--output PATH|-] [--json]",
    "",
    "Examples:",
    "  workbench candidates list --json",
    "  workbench candidates preview --candidate candidate_123 --path SKILL.md --output -",
  ],
  "candidates list": withSourceDirectoryHelp([
    "Usage:",
    "  workbench candidates list [--dir DIR] [--json]",
    "",
    "List local candidates.",
    "",
    "Examples:",
    "  workbench candidates list",
    "  workbench candidates list --json",
  ]),
  "candidates show": withSourceDirectoryHelp([
    "Usage:",
    "  workbench candidates show CANDIDATE_ID [--dir DIR] [--json]",
    "",
    "Show one local candidate.",
    "",
    "Examples:",
    "  workbench candidates show candidate_123",
    "  workbench candidates show candidate_123 --json",
  ]),
  "candidates files": withSourceDirectoryHelp([
    "Usage:",
    "  workbench candidates files [--dir DIR] [--candidate CANDIDATE_ID] [--json]",
    "",
    "List files in a local candidate snapshot.",
    "",
    "Examples:",
    "  workbench candidates files --candidate candidate_123",
    "  workbench candidates files --candidate candidate_123 --json",
  ]),
  "candidates preview": withSourceDirectoryHelp([
    "Usage:",
    "  workbench candidates preview --path PATH [--dir DIR] [--candidate CANDIDATE_ID] [--output PATH|-] [--json]",
    "",
    "Preview a file from a local candidate snapshot.",
    "",
    "Examples:",
    "  workbench candidates preview --candidate candidate_123 --path SKILL.md",
    "  workbench candidates preview --candidate candidate_123 --path SKILL.md --output -",
  ]),
  clone: [
    "Usage:",
    "  workbench clone OWNER/BENCHMARK [DIR] [--dry-run] [--json]",
    "",
    "Clone hosted source and runtime history into a local Workbench project and remember it as the remote.",
    "",
    "Examples:",
    "  workbench clone openbench/invoice-review",
    "  workbench clone openbench/invoice-review ./invoice-review --dry-run --json",
  ],
  pull: withSourceDirectoryHelp([
    "Usage:",
    "  workbench pull [--dir DIR] [--dry-run] [--json]",
    "",
    "Pull source and runtime history from the remembered remote into the local project.",
    "",
    "Examples:",
    "  workbench pull --dry-run",
    "  workbench pull --json",
  ]),
  push: withSourceDirectoryHelp([
    "Usage:",
    "  workbench push [SOURCE] [--dir DIR] [--visibility public|private] [--dry-run] [--json]",
    "",
    "Push local project source and runtime history to the remembered remote, or create one when the project has not been pushed before.",
    "",
    "Examples:",
    "  workbench push --dry-run",
    "  workbench push candidates/current --visibility private --json",
  ]),
  login: [
    "Usage:",
    "  workbench login [--base-url URL] [--no-open] [--json]",
    "",
    "Authenticate this machine with Workbench Cloud.",
    "",
    "Examples:",
    "  workbench login",
    "  workbench login --no-open --json",
  ],
  logout: [
    "Usage:",
    "  workbench logout [--json]",
    "",
    "Remove the stored Workbench Cloud access token.",
    "",
    "Examples:",
    "  workbench logout",
    "  workbench logout --json",
  ],
  whoami: withSourceDirectoryHelp([
    "Usage:",
    "  workbench whoami [--dir DIR] [--json]",
    "",
    "Show the effective Workbench Cloud API target, login status, username, and required adapter auth status.",
    "",
    "Examples:",
    "  workbench whoami",
    "  workbench whoami --json",
  ]),
  adapters: withSourceDirectoryHelp([
    "Usage:",
    "  workbench adapters create PATH [--dir DIR] [--json]",
    "  workbench adapters list [--dir DIR] [--json]",
    "  workbench adapters inspect ID [--dir DIR] [--json]",
    "  workbench adapters test ID|SOURCE [--dir DIR] [--request PATH] [--output DIR] [--json]",
    "",
    "Create, list, inspect, and locally replay Workbench adapters. Adapter sources can be local paths, npm: package refs, or git: refs.",
    "",
    "Examples:",
    "  workbench adapters list --json",
    "  workbench adapters test codex --json",
  ]),
  "adapters create": withSourceDirectoryHelp([
    "Usage:",
    "  workbench adapters create PATH [--dir DIR] [--json]",
    "",
    "Scaffold a benchmark-contained adapter source.",
    "",
    "Examples:",
    "  workbench adapters create adapters/my-agent",
    "  workbench adapters create adapters/my-agent --json",
  ]),
  "adapters list": withSourceDirectoryHelp([
    "Usage:",
    "  workbench adapters list [--dir DIR] [--json]",
    "",
    "List default and project-declared adapters.",
    "",
    "Examples:",
    "  workbench adapters list",
    "  workbench adapters list --json",
  ]),
  "adapters inspect": withSourceDirectoryHelp([
    "Usage:",
    "  workbench adapters inspect ID [--dir DIR] [--json]",
    "",
    "Show one adapter manifest and resolved source.",
    "",
    "Examples:",
    "  workbench adapters inspect codex",
    "  workbench adapters inspect adapters/my-agent --json",
  ]),
  "adapters test": withSourceDirectoryHelp([
    "Usage:",
    "  workbench adapters test ID|SOURCE [--dir DIR] [--request PATH] [--output DIR] [--json]",
    "",
    "Validate an adapter manifest, or replay its command locally when --request is provided. Without --output, replay uses a temporary output directory.",
    "",
    "Examples:",
    "  workbench adapters test codex --json",
    "  workbench adapters test adapters/my-agent --request request.json --output out/adapter-test",
  ]),
  traces: [
    "Usage:",
    "  workbench traces collect [--providers codex,claude] [--since 30d] [--workspace DIR] [--limit N] [--json]",
    "  workbench traces list [--providers codex,claude] [--since 30d] [--workspace DIR] [--limit N] [--json]",
    "  workbench traces show TRACE_ID [--providers codex,claude] [--since 30d] [--workspace DIR] [--json]",
    "",
    "Inspect local installed-agent traces without calling an LLM.",
    "",
    "Examples:",
    "  workbench traces list --limit 10 --json",
    "  workbench traces show codex:SESSION:TRACE --json",
  ],
  "traces collect": [
    "Usage:",
    "  workbench traces collect [--providers codex,claude] [--since 30d] [--workspace DIR] [--limit N] [--json]",
    "",
    "Recover recent local Codex and Claude Code sessions to stdout without calling an LLM. --limit defaults to 3 per provider and output reports when matches were capped.",
    "",
    "Examples:",
    "  workbench traces collect --limit 5 --json",
    "  workbench traces collect --providers codex --workspace . --since 14d",
  ],
  "traces list": [
    "Usage:",
    "  workbench traces list [--providers codex,claude] [--since 30d] [--workspace DIR] [--limit N] [--json]",
    "",
    "List recent local Codex and Claude Code sessions as compact trace rows with ids for follow-up inspection.",
    "",
    "Examples:",
    "  workbench traces list --limit 10 --json",
    "  workbench traces list --providers claude --workspace .",
  ],
  "traces show": [
    "Usage:",
    "  workbench traces show TRACE_ID [--providers codex,claude] [--since 30d] [--workspace DIR] [--json]",
    "",
    "Show one selected local trace digest by exact id.",
    "",
    "Examples:",
    "  workbench traces show codex:SESSION:TRACE --json",
    "  workbench traces show claude:SESSION:TRACE --workspace .",
  ],
  auth: [
    "Usage:",
    "  workbench auth <command> [options]",
    "",
    "Connect adapter auth for local and hosted runs.",
    "",
    "Commands:",
    "  workbench auth connect ADAPTER[/SLOT] [--dir DIR] [--method METHOD] [--profile PROFILE] [--profile-root DIR] [--local-only] [--json]",
    "  workbench auth disconnect ADAPTER[/SLOT] [--profile PROFILE] [--local-only] [--json]",
    "",
    "Examples:",
    "  workbench auth connect codex --method oauth --json",
    "  workbench auth disconnect codex --local-only",
  ],
  "auth connect": [
    "Usage:",
    "  workbench auth connect ADAPTER[/SLOT] [--dir DIR] [--method METHOD] [--profile PROFILE] [--profile-root DIR] [--local-only] [--json]",
    "",
    "Connect adapter auth using a manifest-supported method.",
    "",
    "Examples:",
    "  workbench auth connect codex --method oauth --json",
    "  workbench auth connect claude --method api-key --profile default --local-only",
  ],
  "auth disconnect": [
    "Usage:",
    "  workbench auth disconnect ADAPTER[/SLOT] [--profile PROFILE] [--local-only] [--json]",
    "",
    "Disconnect adapter auth locally and, when logged in, in hosted Workbench.",
    "",
    "Examples:",
    "  workbench auth disconnect codex --local-only",
    "  workbench auth disconnect claude --profile default --json",
  ],
}).map(([key, lines]) => [key, lines.join("\n")]));

export function commandUsage(commandPath: string): string | null {
  return commandHelp[commandPath] ?? null;
}
